### ISSUE TITLE
PyAttract and Heligeom as submodules?

### ISSUE THREAD

**Issue by benoistlaurent** [ptools/ptools-legacy#45]
Right now Heligeom and PyAttract provide qui a lot of functions but are not installed.
Should those directories be included as ptools submodules?

I think it could be the first step into a much powerful PTools in which one could use basically every
class/function that have been implemented for Heligeom or PyAttract.

Example:

``` python
from ptools.PyAttract import attract

# ... do something before
params = attract.readParams(filename)
# ... do something after
```

Eventually, those directories should be renamed to fit Python [PEP-8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) conventions for module naming.

**Comment by charlestonchas** [comment]
I'm 100% in favour of this idea.

I suggested exactly this to Chantal when we wrote the tests for heligeom.py in 2015. At that time, as a demonstration, I tried to modify my local version of the setup.py to install heligeom as a module (I say "module" instead of "submodule" because for me ptools is a package, not a module). But my attempt failed because I didn't understand the logic of setup.py well enough.

**Comment by pierrepo** [comment]
I agree too.
This is definitely the way we have to handle PTools functionalities.
Of course, we'll provide -- along the documentation or as separated files -- extensive examples of how to use these (sub)modules.

**Comment by benoistlaurent** [comment]
- `PyAttract` will be renamed into `attract`.
- I/O functions will be coded the module `ptools/io.py`.
- Other functions will be coded in the submodule `ptools/attract/<file>.py`.

**Comment by benoistlaurent** [comment]
* attract done in 18e6bdd
* heligeom done in 6820fab
