### ISSUE TITLE
MatTrans2screw not available for import

### ISSUE THREAD

**Issue by charlestonchas** [ptools/ptools-legacy#65]
Can't import MatTrans2screw from ptools
>>> from ptools import *
>>> MatTrans2screw()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'MatTrans2screw' is not defined

**Comment by chantalprevost** [comment]
After verification, MatTrans2screw, and more generally the whole screw class, are defined in C++ (superpose.cpp) but are not transferred to python in the cython pyx files.

**Comment by benoistlaurent** [comment]
Fixed by 9902b7b

**Comment by chantalprevost** [comment]
Bonjour Benoist,

Tu as donc réussi à passer le MatTrans2screw ? super !

Je te joins des fichiers à tester avec le script heligeom.py, qui utilise MatTrans2screw (test fonctionnel).

La commande est :
python heligeom.py 2GLS_A.pdb 2GLS_B.pdb 

et ça doit sortir (sortie standart) le contenu de 2GLS.out

Il peut y avoir une différence au niveau de "Helix direction", et ça pourrait être une bonne nouvelle.
Dis-moi ce que tu obtiens.
 
A + (je serai au labo demain, mais avec un visiteur)

Chantal

----- Mail original -----
De: "Benoist LAURENT" <notifications@github.com>
À: "ptools/ptools" <ptools@noreply.github.com>
Cc: "chantal" <chantal@ibpc.fr>, "Comment" <comment@noreply.github.com>
Envoyé: Lundi 27 Février 2017 14:33:35
Objet: Re: [ptools/ptools] MatTrans2screw not available for import (#65)

Closed #65.

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/ptools/ptools/issues/65#event-978338564
