### ISSUE TITLE
MacOS: Tests/cpp/Makefile g++ include path missing /opt/local/include

### ISSUE THREAD

**Issue by charlestonchas** [ptools/ptools-legacy#70]
-- Error

        g++ -mmacosx-version-min=10.9 -O2 -I. -I../../headers -o ptoolstest.bin runner.cpp ../../build/lib.macosx-10.10-x86_64-2.7/_ptools.so -lpython2.7
        In file included from ../../headers/coord3d.h:10:0,
                         from ptoolstest.h:1,
                         from runner.cpp:17:
        ../../headers/basetypes.h:37:34: fatal error: boost/shared_array.hpp: No such file or directory
         #include <boost/shared_array.hpp>
                                          ^

-- Solution
Add `-I/opt/local/include` to g++ command line in Tests/cpp/Makefile. (But could this Makefile be generated by setup.py?)

**Comment by benoistlaurent** [comment]
This problem is specific to the `Tests/cpp/Makefile` which compiles unit tests for PTools C++ functions.

The only way I see to solve this is to write a function is the setup script that would write this Makefile with appropriate paths found thanks to the setup script `find_[file|directory]` functions.

**Comment by charlestonchas** [comment]
I already did that. It will be in my merge or pull request for macos-specific changes.
